### ISSUE TITLE
[Feature Request] Add support for RC-5 protocol for Remote Transmitter and Receiver

### ISSUE THREAD

**Issue by flozsc** [esphome/ESPHome-Core#130]
Hello Otto,

Thank you so much for your efforts on this library and tool chain.

I own a Philips TV, which unfortunately uses the RC-5 protocol unsupported by esphomelib and I'd prefer using the protocol over the raw bits captured. Would it be hard to implement it into esphomelib?
I found some code for it in the IRremoteESP8266 library: https://github.com/markszabo/IRremoteESP8266/blob/master/src/ir_RC5_RC6.cpp

I could also try adding it by myself and sending a PR. In that case I'd be grateful if you could provide me with some rough instructions how to do it in the way you designed the library in order to not break anything. :)

Thanks in advance!
Florian

**Comment by davericher** [comment]
I used LIRCs capture feature that then seems to refactor everything down to a 32bit LG code. A few extra steps, but no raws required inside the code.

**Comment by OttoWinter** [comment]
https://github.com/esphome/feature-requests/issues/10
