### ISSUE TITLE
Custom Sensor - how to access to Remote receiver or I2C component

### ISSUE THREAD

**Issue by NicoFR75** [esphome/ESPHome-Core#160]
Hello,

Is it possible to query a remote receiver or an i2c component (previously declared in the yaml config file) from a custom sensor ?

I've a project where i want to receive analog sensor values transmitted over RF which idealy would be encrypt with xxxtea and using virtualwire library. If i can't use the esp8266 for receiving directly RF signal, i could use an arduino for doing the job, store values and then use it as an i2c slave to get the sensor value.

Thanks for your help.

**Comment by OttoWinter** [comment]
It would be possible to directly use the remote receiver component, but I guess it would be a bit complicated. I don't know about this virtualwire protocol, but it would look something like this:

```cpp
class MyCustomReceiver : public remote::RemoteReceiver, public sensor::Sensor {
  public:
    MyCustomReceiver(const std::string &name) : RemoteReceiver(name), Sensor(name) {}

    bool matches(RemoteReceiveData *data) override {
      // implement virtualwire protocol here, data is the data that was just received
      // note: you would have to actually implement the virtualwire protocol, you cannot just use the library.
      this->push_new_value(my_sensor_value);

      return false;
    }
};

// in setup()
auto *receiver = new MyCustomReceiver("The name");
the_remote_receiver->add_decoder(receiver);

App.register_sensor(receiver);
```

So basically, you're overriding `matches` so that you can decode the data. **Warning:** This is complicated as you will have to implement the full virtualwire protocol.

The easier way, as you stated, would be to use an Arduino as a "converter". Note that the arduino would have to be the i2c master. Basically, then you could just do:

```cpp
class MyCustomSensor : public sensor::PollingSensorComponent {
 public:
  MyCustomSensor(const std::string &name, uint32_t update_interval)
      : sensor::PollingSensorComponent(name, update_interval) {

  }

  void setup() override {
    // If you have i2c: in your config you don't need to call this.
    // Wire.begin()
  }

  void update() override {
    // your i2c protocol, for example
    Wire.requestFrom(the_i2c_address, 1);
    int a = Wire.read();
    this->push_new_value(a);
  }

  std::string unit_of_measurement() override { return "TODO"; }
  int8_t accuracy_decimals() override { return 42; }
};

// register as in custom sensor guide
```

**Comment by NicoFR75** [comment]
Thanks for your answer, the 2nd method looks much easier. 

But you're saying that the arduino needs to be the i2c master, why ? 
I tought that the "_Wire.requestFrom_" was for querying i2c slave.

Another question, in the 1st method does the "_RemoteReceiveData *data_" contains the received data in raw format ?

Thanks
