### ISSUE TITLE
Custom Fan Speeds 

### ISSUE THREAD

**Issue by deerhunter91** [esphome/ESPHome-Core#450]
**Is your feature request related to a problem/use-case? Please describe.**

The ability to set more fan speeds than just low, medium and high would be useful for fans that have more than just three settings. 

**Describe the solution you'd like**

Be able to define custom fan speeds. For example:

Off
Very Quite
Low
Medium 
Fast
Full Speed

**Additional context**

Being able to have a slider for fans that are variable would also be nice to have.

**Comment by OttoWinter** [comment]
We're limited by Home Assistant here. Home Assistant only supports the fan speeds you see right now.
