### ISSUE TITLE
MIC sensor, status fast change

### ISSUE THREAD

**Issue by Iv711** [esphome/esphome-core#547]
Hi! (Im sorry for my English, this is all Google;))
I use the microphone sensor, but if the noise occurs and quickly subsides, the sensor status quickly changes **off-on-off**. Is it possible to make a status delay after triggering, so that the **on** status would remain at least 10 seconds?

**Comment by OttoWinter** [comment]
https://github.com/esphome/esphome-core/issues/499

see binary sensoe gpio page please
